### ISSUE TITLE
Installation Causes Mautic to Crash

### ISSUE THREAD

**Issue by mrgrosser** [LucasCCS/postal_server_api_transport_for_mautic#4]
After following documentation, I tried creating the directory, removing everything from cache and running the php command the server fails to respond. I thinking blowing away the cache in version 5 is a bad move. 
Is there another way to install this that has been tested in Version 5?

**Comment by fanpero87** [comment]
I also have issues with Mautic 5.0.2.
I made the folder under plugins and clone the repo. When I ran `php bin/console mautic:plugins:reload`
I got the following error:
```
PHP Fatal error:  Uncaught Error: Class "Mautic\EmailBundle\Model\TransportType" not found in /srv/mautic/plugins/MauticPostalServerBundle/Config/config.php:34
Stack trace:
#0 /srv/mautic/app/bundles/CoreBundle/Loader/ParameterLoader.php(143): include()
#1 /srv/mautic/app/bundles/CoreBundle/Loader/ParameterLoader.php(33): Mautic\CoreBundle\Loader\ParameterLoader->loadDefaultParameters()
#2 /srv/mautic/app/AppKernel.php(358): Mautic\CoreBundle\Loader\ParameterLoader->__construct()
#3 /srv/mautic/app/AppKernel.php(228): AppKernel->getParameterLoader()
#4 /srv/mautic/vendor/symfony/framework-bundle/Console/Application.php(168): AppKernel->boot()
#5 /srv/mautic/vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#6 /srv/mautic/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#7 /srv/mautic/bin/console(16): Symfony\Component\Console\Application->run()
#8 {main}
  thrown in /srv/mautic/plugins/MauticPostalServerBundle/Config/config.php on line 34
```

Maybe the plugin doesnt work on Mautic5 ?

**Comment by fanpero87** [comment]
This plugin is not compatible with Mautic5. It does work fine with Mautic 4.4.12.
